# Generated by Django 3.2.9 on 2021-12-13 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describtion', models.TextField()),
                ('publishdate', models.DateField(default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
